# RoleBinding: bind Role laravel-app-reader to ServiceAccount laravel-app
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: laravel-app-reader
  namespace: pi-k3s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: laravel-app-reader
subjects:
  - kind: ServiceAccount
    name: laravel-app
    namespace: pi-k3s
