apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: pi-k3s
type: Opaque
data:
  APP_KEY: YmFzZTY0OnhUbEVZUjBLUlhmT2ZDTXlzZENUcU9OMWNJa3dPQlFCSVE3OEZDL2JvWms9

  # Database credentials (placeholder)
  DB_PASSWORD: ""
