apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: pi-k3s
  labels:
    app: laravel
    component: web
spec:
  type: ClusterIP
  selector:
    app: laravel
    component: web
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
